config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  resources 'articles' do
    resources 'comments'
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  http_basic_authenticate_with name: Settings.authentication.name, 
                               password: Settings.authentication.password, 
                               except: [:index, :show]

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    render('new') and return unless @article.save
    redirect_to(@article)
  end

  def show
    @article = Article.find(params[:id])
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    render 'edit' and return unless @article.update(article_params())
    redirect_to @article
  end

  def destroy
    article = Article.find(params[:id])
    article.destroy
    redirect_to article
  end

  private

  def article_params
    params.require(:article).permit(:title, :body)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  http_basic_authenticate_with name: Settings.authentication.name, 
                               password: Settings.authentication.password, 
                               only: [:destroy]

  def create
    @article = Article.find(params[:article_id])
    # comment = Comment.new(text: params[:comment][:text], article_id: params[:article_id])
    # comment.save
    @comment = @article.comments.create(comment_params())
    redirect_to @article
  end

  def destroy
    @article  = Article.find(params[:article_id])
    # @comment = Comment.find(params[:id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy

    redirect_to @article
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
  <% if @article.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@article.errors.count, 'error') %> prohibited this article to save.</h2>
    <ul>
    <% @article.errors.full_messages.each do |message| %>
      <li><%= message%></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1>Index Page</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Title</th>
      <th>Body</th>
      <th>Oprations</th>
    </tr>
  </thead>
  <tbody>
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.id %></td>
      <td><%= article.title %></td>
      <td><%= article.body %></td>
      <td>
        <%= link_to 'View', article_path(article.id) %>
        <%= link_to 'Edit', edit_article_path(article.id) %>
        <%= link_to 'Destroy', article_path(article.id), method: :delete, data: { confirm: 'Are you sure?'} %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<div>
  <%= link_to 'Add a new Article', new_article_path %>
</div>

app/views/articles/new.html.erb
<h1>Create Article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h1>Article Details</h1>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @article.body %>
</p>

<p>
  <%= link_to 'Articles', articles_path %>
</p>

<h2>Comments</h2>
<%= render @article.comments  %>

<h2>Add a Comment:</h2>
<%= render 'comments/form' %>

<%= link_to 'Edit Article', edit_article_path(@article.id)  %> |
<%= link_to 'Back to Articles', articles_path  %>

app/views/comments/_comment.html.erb
<p>
  <%= comment.commenter %> said: <%= comment.body %>
  <%= link_to 'Destroy', article_comment_path(@article.id, comment.id), method: :delete, data: { confirm: 'Are you sure?'} %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build])  do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>